spring.application.name=api-gateway

server.port=8080

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

spring.main.web-application-type=reactive

# Route 1: User Service (Handles all /api/auth/** requests)
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# Route 2: Product Service (Handles all /api/products/** requests)
spring.cloud.gateway.routes[1].id=product-service
spring.cloud.gateway.routes[1].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/products/**


# --- Bidding Service Route ---
spring.cloud.gateway.routes[2].id=bidding-service
spring.cloud.gateway.routes[2].uri=lb://BIDDING-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/bids/**
