# --- 1. Basic Server Setup ---
server.port=8084
spring.application.name=NOTIFICATION-SERVICE

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.rabbitmq.addresses=amqps://rcsdryiv:W46jyAmaRRkYRPLvxemsgh9YM2Deg8up@puffin.rmq2.cloudamqp.com/rcsdryiv

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=prasannareddymotati02@gmail.com
spring.mail.password=nvhbupvlicvuxlko
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true